name: Deploy from React.js

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
